
[build]
  command = "curl -L https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.361/quarto-linux-amd64.tar.gz | tar -xz && ./quarto/bin/quarto render"
  publish = "_site"


[build.environment]
  R_LIBS_USER = "/opt/buildhome/R/lib/R/library"