[build]
  command = "curl -sSL https://github.com/quarto-dev/quarto-cli/releases/latest/download/quarto-linux-amd64.deb -o quarto.deb && dpkg -i quarto.deb && quarto render"
  publish = "_site"

[build.environment]
  R_LIBS_USER = "/opt/buildhome/R/lib/R/library"